kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: build
    image: docker:latest
    commands:
      - docker build -t app-name-env-mode:DRONE_BUILD_NUMBER .
      
  - name: deploy
    image: docker:latest
    commands:
      - docker run -d --restart=always -u 0 --name app-name-env-mode -e APP_NAME=app-name -e CONSUL_ADDRESS=consul-address -m 512m --cpus=1 app-name-env-mode:DRONE_BUILD_NUMBER
